spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  jpa:
    show-sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads
app:
  storage:
    location: uploads