spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: tasteapptracker@gmail.com
    password: mtegalztotmljnqh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  accountactivation:
    template: templates/message/account-activation-message.html
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
